name: alarm_bayi
description: "Advanced Baby Monitor Alarm System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.1
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.2.0
  js: ^0.7.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Audio & Background Services
  audioplayers: ^6.4.0 # Diperbarui dari ^5.2.1
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.3.1

  # UI & Navigation
  go_router: ^14.2.8
  gap: ^3.0.1

  # Utilities
  uuid: ^4.5.0
  intl: ^0.19.0
  shared_preferences: ^2.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
