// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGhIUUQBNU4cVnVgDt1anS_bpevT0t9Y',
    appId: '1:1026596677029:web:ac5fc79bac70bad81bf44c',
    messagingSenderId: '1026596677029',
    projectId: 'alarm-bayi-project',
    authDomain: 'alarm-bayi-project.firebaseapp.com',
    storageBucket: 'alarm-bayi-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhlD5WbZMLEuAvL4EFY0kN5J_ZzS6yz8E',
    appId: '1:1026596677029:android:adc18d8019548b9e1bf44c',
    messagingSenderId: '1026596677029',
    projectId: 'alarm-bayi-project',
    storageBucket: 'alarm-bayi-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnsPeKVdgXmJRSeZ7r0uL7WDxCl58sOFs',
    appId: '1:1026596677029:ios:e94f4b73d2e4e1151bf44c',
    messagingSenderId: '1026596677029',
    projectId: 'alarm-bayi-project',
    storageBucket: 'alarm-bayi-project.firebasestorage.app',
    iosBundleId: 'com.example.alarmBayi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnsPeKVdgXmJRSeZ7r0uL7WDxCl58sOFs',
    appId: '1:1026596677029:ios:e94f4b73d2e4e1151bf44c',
    messagingSenderId: '1026596677029',
    projectId: 'alarm-bayi-project',
    storageBucket: 'alarm-bayi-project.firebasestorage.app',
    iosBundleId: 'com.example.alarmBayi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgGhIUUQBNU4cVnVgDt1anS_bpevT0t9Y',
    appId: '1:1026596677029:web:0c26535dcaeedc421bf44c',
    messagingSenderId: '1026596677029',
    projectId: 'alarm-bayi-project',
    authDomain: 'alarm-bayi-project.firebaseapp.com',
    storageBucket: 'alarm-bayi-project.firebasestorage.app',
  );
}
